// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiebh5PRrTl4T9GJk0oK1rd2n6rTXZ5-0',
    appId: '1:949465561283:web:d2ed3a8f7bf1e8b7cc0a76',
    messagingSenderId: '949465561283',
    projectId: 'explore-2aed1',
    authDomain: 'explore-2aed1.firebaseapp.com',
    databaseURL: 'https://explore-2aed1.firebaseio.com',
    storageBucket: 'explore-2aed1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7bSRFHS8vnKKEui1gadssd0BcPTbTxVg',
    appId: '1:949465561283:android:b62dd95829f8915ecc0a76',
    messagingSenderId: '949465561283',
    projectId: 'explore-2aed1',
    databaseURL: 'https://explore-2aed1.firebaseio.com',
    storageBucket: 'explore-2aed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOIopfGyEXZUrQu4XmquZazi989z_Nhvw',
    appId: '1:949465561283:ios:cb641a0aa87ab2f5cc0a76',
    messagingSenderId: '949465561283',
    projectId: 'explore-2aed1',
    databaseURL: 'https://explore-2aed1.firebaseio.com',
    storageBucket: 'explore-2aed1.appspot.com',
    iosClientId: '949465561283-71fimomngeg7clgtjl3ff4dje22mlhj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.explore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOIopfGyEXZUrQu4XmquZazi989z_Nhvw',
    appId: '1:949465561283:ios:d2e1339d6ae03eafcc0a76',
    messagingSenderId: '949465561283',
    projectId: 'explore-2aed1',
    databaseURL: 'https://explore-2aed1.firebaseio.com',
    storageBucket: 'explore-2aed1.appspot.com',
    iosClientId: '949465561283-ueat79p0giquhvas6bm1s872vcn36dgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.explore.RunnerTests',
  );
}
